### ISSUE TITLE
Missing `=>` after `add_metadata_from_env` in logstash-filter-environment plugin doc

### ISSUE THREAD

**Issue by kosho** [elastic/logstash-docs#220]
It seems some errors appear in `logstash-filter-environment` plugin doc.

Error: `filter { environment { add_metadata_from_env { "field_name" ⇒ "ENV_VAR_NAME" } } }`
Should be: `filter { environment { add_metadata_from_env => { "field_name" => "ENV_VAR_NAME" } } }`

`=>` is missing after `add_metadata_from_env` and an unicode character appears after `"field_name"` instead of `=>`.
`add_metadata_from_env` appears three times in: https://www.elastic.co/guide/en/logstash/2.3/plugins-filters-environment.html and all of them miss `=>` after `add_metadata_from_env`.

And the metadata filed could be given `"%{[@metadata][event_type]}"`, not `["@metadata"]["field_name"]` in this context.

Thank you!

**Comment by dedemorton** [comment]
Closing this issue because logstash-docs is meant to be a read-only repo. It looks like the formatting issue you noted has been fixed with the latest updates to our doc generation tool.

If there are any remaining issues with this content, please create an issue in the repo for the plugin:
https://github.com/logstash-plugins/logstash-filter-environment
