### ISSUE TITLE
~ characters are not shown

### ISSUE THREAD

**Issue by spuder** [elastic/logstash-docs#70]
Due to the way asciidoc special characters are escaped. There are many instances in the docs where special characters such as `~` do not appear. 

One examples is this page. 

http://www.elastic.co/guide/en/logstash/current/configuration.html#conditionals

This line is missing the `~` characters

* regexp: =~, !~

I tried making a pull request, but all my attempts to fix it failed. 

http://www.methods.co.nz/asciidoc/faq.html#_some_elements_can_8217_t_be_escaped_with_a_single_backslash

None of the following work.

```
regexp: =\~, !\~
regexp: =\\~, !\\~
regexp: \\ =~, !~
```

**Comment by untergeek** [comment]
Thanks for catching this and attempting to fix it.  The fix is to put the offenders inside back-ticks, e.g.

> regexp: `=~`, `!~` 

And we have a two-stage doc process where we render docs from the regular logstash repo, plus docs rendered from different Logstash plugins (still a fairly manual process).  Because of this, we prefer pull requests from the actual repositories.  The [README](https://github.com/elastic/logstash-docs/blob/master/README.md) for this site says that it's a generated repository, please don't edit.  

Pull requests to fix the docs need to be in the regular logstash repo in the docs tree.  In this case, the file is at: https://github.com/elastic/logstash/blob/master/docs/asciidoc/static/configuration.asciidoc

**Comment by untergeek** [comment]
We've fixed the "edit" links in our documentation to point to the correct repository.  Again, please go back to the docs and click the "edit" link to correct these docs.   It will now take you to the correct repository, where the edit needs to take place.  The way to fix these characters is to use back-ticks to encapsulate the offending code examples.

**Comment by spuder** [comment]
Looks like someone already fixed it. 

https://github.com/elastic/logstash/commit/b663f9ff614813f264d006ccd966551927c4ade1#diff-56e84293fa738d81a605fc3e29741e28
